- hosts: all
  connection: local
  tasks:
  - name: add static routes
    vyos_config:
      lines:
        - set protocols static route 12.1.1.0/24 next-hop 192.168.18.179
        - set protocols static route 192.168.68.128/26 next-hop 192.168.1.4
        - set protocols static route 192.168.69.128/26 next-hop 192.168.1.5
        - set protocols static route 192.168.70.128/26 next-hop 192.168.1.6  

