{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eechart.serviceAccountName" . }}
  labels:
{{ include "eechart.labels" . | indent 4 }}
{{- end -}}
