apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "eechart.fullname" . }}
  labels:
{{ include "eechart.labels" . | indent 4 }}
spec:
  serviceName:  {{ include "eechart.fullname" . }} 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eechart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eechart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        vnf: {{ .Values.global.osm.vnf_id | lower}}
    spec:
      imagePullSecrets:
      - name: regcred 
      serviceAccountName: {{ template "eechart.serviceAccountName" . }}
      securityContext:
        runAsUser: 0
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "eechart.fullname" . }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}          
          volumeMounts:
          - name: osm-ee
            mountPath: /app/storage  
          - name: osm-ee-source
            mountPath: /app/EE/osm_ee/vnf      
          - name: snmp-config-volume
            mountPath: /etc/snmp_exporter
          - name: vnf-mibs
            mountPath: /root/.snmp/mibs
          - name: vnf-generator
            mountPath: /app/vnf/generator
      volumes:      
      - name: osm-ee-source
        configMap: 
          name:  {{ include "eechart.fullname" . }}
      - name: snmp-config-volume
        hostPath: 
          path: "/var/lib/osm/snmp_exporter/{{ .Values.global.osm.vnf_id | lower }}/"
      - name: vnf-mibs
        configMap:
          name: "vnf-snmp-mibs-{{ .Values.global.osm.vnf_id | lower}}"
      - name: vnf-generator
        configMap:
          name: "vnf-snmp-generator-{{ .Values.global.osm.vnf_id | lower}}"
      - name: osm-ee
        hostPath:
          path: /var/lib/osm/osm/osm_osm_packages/_data
