apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eechart.fullname" . }}
type: Opaque
data:
  mysql_host: {{ .Values.mysql.fullnameOverride | b64enc | quote }}
  mysql_user: {{ "root" | b64enc | quote }}
  mysql_password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
